### ISSUE TITLE
landsat_search seems to max at around 2018-07-30

### ISSUE THREAD

**Issue by wcrice** [atlanhq/rLandsat#10]
When I run a search using landsat_search I seem to only get results before 2018-04-29. The USGS, AWS, and Google all have images after that but the tool doesn't seem to give results for them. Is this a known issue or is there a workaround?

Searching for dates after 2018-07-30 give no results.

## Expected Behavior

Searching for dates after 2018-07-30 should give results.
## Current Behavior

No results
## Steps to Reproduce

1. result = landsat_search(min_date = "2018-07-30", max_date = "2019-06-16", country = "India")
2.
3.
4.

**Comment by himanshu-sikaria** [comment]
Hi. This could be a bug from the API rLandsat uses in the background (sat-api). A way around of it could be changing the source to either "aws" or "usgs" (preferred)

`result = landsat_search(min_date = "2018-07-30", max_date = "2019-06-16", country = "India", source = "usgs")`

This should solve the problem. Closing the issue for now. Reopen if this doesn't work @wcrice
