### ISSUE TITLE
Order Failed!

### ISSUE THREAD

**Issue by PMassicotte** [atlanhq/rLandsat#7]
Order Failed!

## Expected Behavior
Order Succeeded!

## Current Behavior
Order Failed!

## Steps to Reproduce

I replaced *yourusername* and *yourpassword* with appropriate information.

```r
library(rLandsat)

result = landsat_search(min_date = "2018-01-01", max_date = "2018-01-16", country = "India")

# inputting espa creds
espa_creds("yourusername", "yourpassword")

# getting available products
prods = espa_products(result$product_id)
prods = prods$master

# placing an espa order
result_order = espa_order(result$product_id, product = c("sr","sr_ndvi"),
                          projection = "lonlat",
                          order_note = "All India Jan 2018")
```

**Comment by himanshu-sikaria** [comment]
The possible reasons why the order might have failed - 
1. A product ID is requested which USGS has removed or reprocessed and changed the ID. A possible solution for this is to add a parameter `source="usgs"` in the `landsat_search` function. 
2. A requested product (in this case "sr", "sr_ndvi") is not available for all the product IDs. For this you can check the `prods` data frame which is created.

**Comment by himanshu-sikaria** [comment]
You can also check `result_order$response` to know the exact reason why the order has failed. Would be easier to debug from there. @PMassicotte

**Comment by PMassicotte** [comment]
Hi.

The response is:

```r
> result_order$response
Response [https://espa.cr.usgs.gov/api/v1/order]
  Date: 2019-04-05 12:07
  Status: 500
  Content-Type: application/json
  Size: 37 B
{"message": "Internal Server Error"}
```

**Comment by himanshu-sikaria** [comment]
It could be that ESPA USGS was down for maintenance. Would request you to retry
