### ISSUE TITLE
‘rLandsat’ is not available (for R version 3.5.2)

### ISSUE THREAD

**Issue by FrancescoReyes** [atlanhq/rLandsat#8]
All simply, 
when installing the rLandsat package:

``install.packages("rLandsat")
Installing package into ‘C:/Users/Ut1/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
package ‘rLandsat’ is not available (for R version 3.5.2)

for whar R version is rLandsat available?

**Comment by himanshu-sikaria** [comment]
Please install rLandsat from github directly. `devtools::install_github("atlanhq/rLandsat")`
