### ISSUE TITLE
Error in function (type, msg, asError = TRUE)  :    Unknown SSL protocol error in connection to edclpdsftp.cr.usgs.gov:443 

### ISSUE THREAD

**Issue by arnaudmilet** [atlanhq/rLandsat#9]
When I try to apply the example:
durl = espa_status(order_id = order_id, getSize = TRUE)

I've got an error with this message:
Error in function (type, msg, asError = TRUE)  :    Unknown SSL protocol error in connection to edclpdsftp.cr.usgs.gov:443 

Do you have any idee?
Thank you
Arnaud

**Comment by bravemaster3** [comment]
I also got the same error, and I don't know what it means. Did you find something finally?

**Comment by himanshu-sikaria** [comment]
This could be an error from USGS. There are times when USGS ESPA is down. You can try logging in here https://espa.cr.usgs.gov/ordering/status/

Else, please give a order id as example so that I can reproduce the error.

**Comment by himanshu-sikaria** [comment]
I ran the following and it worked as expected. 
```
library(rLandsat)
espa_creds("user", "password")
data = landsat_search(max_date = "2019-02-01", min_date = "2019-01-01", path_master = 147, row_master =  48, source = "usgs")
order = espa_order("LC08_L1TP_147048_20190129_20190206_01_T1", product = "sr")
order
espa_status("espa-himanshu.sikaria@xxxxxxxxxxxxx")
```

**Comment by bravemaster3** [comment]
Thank you @himanshu-sikaria for your comment.
You are right, it was not working for some of the images, but some work.

**Comment by himanshu-sikaria** [comment]
Good to know. Closing the issue
